version: '2'

services:
  web-server:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./src:/var/www/html
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
      - mariadb

  php-fpm:
    image: php-fpm
    build:
      context: ./docker
    env_file:
      - .env
    volumes:
      - ./src:/var/www/html

  mariadb:
    image: mariadb:10.6
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - db-data:/var/lib/mysql/data

volumes:
  db-data: